[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
business_app = "2cE9Naq1VKCKTt2DvYoLfR1U6jS5tBpa8PFckbj8aB3p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/shan/key.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
